{{- range .Values.nodes }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
data:
  config.json: |
    {
      "Nodename": "{{ .name | title }}",
      "MetricsNeighbourNodes": [
        {{- $length := len $.Values.nodes }}
        {{- $lastIndex := sub $length 1 }}
        {{- range $index, $elem := $.Values.nodes }}
        {{- if ne .name $.name }}
        {
          "name": "{{ $elem.name | title }}",
          "ip": "{{ $elem.ip }}",
          "rttInterval": {{ $elem.metrics.rttInterval }},
          "throughputInterval": {{ $elem.metrics.throughputInterval }},
          "jitterInterval": {{ $elem.metrics.jitterInterval }}
        }{{ if not (eq $index $lastIndex) }},{{ end }}
        {{- end }}
        {{- end }}
      ]
    }
---
{{- end }}
