apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lpm-{{ .Values.global.network.name}}-network-topology-manager
rules:
  - apiGroups: ["qos-scheduler.siemens.com"]
    resources: ["networktopologies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
