apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-{{.Values.global.network.name}}
spec:
  selector:
    matchLabels:
      app: prometheus-{{.Values.global.network.name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-{{.Values.global.network.name}}
    spec:          
      serviceAccountName: {{.Values.global.network.name}}-sa
      containers:
        - name: prometheus
          image: prom/prometheus:v2.30.3
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: data-volume
              mountPath: /prometheus
        - name: exporter
          image: alpine
          command: ["/bin/ash", "-c", "sleep infinity & wait"]
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config-{{.Values.global.network.name}}
        - name: data-volume
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-{{.Values.global.network.name}}
spec:
  selector:
    app: prometheus-{{.Values.global.network.name}}
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090

